email:
  username: truonganhtuan3092@gmail.com
  password: ckkwnmtyalfzhjjv
server:
  port: 8181
  servlet:
    session:
      timeout: 30m 
spring:          
  application:
    name: SpringSecurityDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: PhuongTay110903@
    url: jdbc:mysql://localhost:3306/spring_security_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 782433930000-guiga98vehpc3dde7vm2d2isgmhti1qr.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 1107629427201806
            client-secret: 1cb2ee2b2459ee33cd90ed8666eec77f
            scope:
             - email
             - public_profile
